bar/urls.py
from django.urls import path
from .api import *
from .views import *
from django.views.generic import TemplateView


app_name = "bar"


router = routers.DefaultRouter()
router.register('metrics', MetricViewSet)
router.register('metric-systems', MetricSystemViewSet)
router.register('orders', OrderViewSet)
router.register('order-groups', OrderGroupViewSet)
router.register('products', ProductViewSet)
router.register('profiles', ProfileViewSet)
router.register('sale-guides', SaleGuideViewSet)
router.register('stock', StockViewSet)
router.register('categories', CategoryViewSet)


urlpatterns = [
	url(r'^api/', include(router.urls)),
	path('', index, name='index'),
	path('home', TemplateView.as_view(template_name='pages/trial.html'), name='index'),
	path('login', login_view, name='login'),
	path('login/waiter/<int:id>', login_waiter, name='login_waiter'),
	path('logout', logout_view, name='logout'),
	
	path('orders', orders, name='orders'),
	path('orders/create', create_orders, name='create_orders'),
	# path('orders/update/<int:order_group_id>', update_orders, name='update_orders'),
	path('orders/update/status', update_order_status, name='update_order_status'),
	path('orders/sales', get_order_sales, name='get_order_sales'),
	
	path('order-groups', get_order_groups, name='get_order_groups'),
	path('order-groups/<int:id>', get_order_group, name='get_order_group'),
	path('order-groups/<int:id>/update', update_order_group, name='update_order_group'),
	path('order-groups/<int:id>/open-or-close', open_or_close_order_group, name='open_or_close_order_group'),
	path('order-groups/<int:id>/delete', delete_order_group, name='delete_order_group'),
	
	path('purchases', get_purchases, name='get_purchases'),

	path('profile', get_current_user_profile, name='get_current_user_profile'),
	path('profile/update', update_current_user_profile, name='update_current_user_profile'),
	path('profile/password/update', update_current_user_password, name='update_current_user_password'),

	path('profiles', get_profiles, name='get_profiles'),
	path('profiles/<int:id>', get_profile, name='get_profile'),
	path('users/create', create_user, name='create_user'),
	path('users/<int:id>', update_user, name='update_user'),
	path('users/<int:id>/delete', delete_user, name='delete_user'),
	path('users/<int:id>/password/update', update_user_password, name='update_user_password'),
	path('users/<int:id>/permissions/update', update_user_permissions, name='update_user_permissions'),


	path('metric-systems', MetricSystemsPageView.as_view(), name='get_metric_systems'),
	path('metric-systems/create', create_metric_system, name='create_metric_system'),
	path('metric-systems/<int:id>/delete', delete_metric_system, name='delete_metric_system'),

	path('products', get_products, name='get_products'),
	path('products/create', create_product, name='create_product'),
	path('products/<int:id>/', get_product, name='get_product'),
	path('products/<int:id>/purchasing/update', update_product_purchasing, name='update_product_purchasing'),
	path('products/<int:id>/delete', delete_product, name='delete_product'),
	path('products/<int:id>/categories/update', update_product_categories, name='update_product_categories'),
	path('products/<int:id>/stock/add', add_product_stock, name='add_product_stock'),

	path('categories/create', create_category, name='create_category'),
	path('categories/<int:id>/', get_category, name='get_category'),
	path('categories/<int:id>/delete', delete_category, name='delete_category'),

	path('notifications', get_notifications, name='get_notifications'),
	path('notifications/count', get_notification_count, name='get_notification_count'),

]

bar_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('bar.urls', namespace='bar')),
]

bar/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import STATUS_CHOICES, PENDING, PAID


# Create your models here.
class TimeStampedModel(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True


class MetricSystem(TimeStampedModel):
	name = models.CharField(max_length=128)
	is_standard = models.BooleanField(default=False)

	def __str__(self):
		return self.name

	def base_metric(self):
		return self.metric_set.filter(multiplier=1.0).first()

	def convert(self, quantity, from_metric, to_metric):
		return quantity*(to_metric.multiplier/from_metric.multiplier)


class Metric(TimeStampedModel):
	unit = models.CharField(max_length=128)
	symbol = models.CharField(max_length=64)
	multiplier = models.FloatField()
	metric_system = models.ForeignKey(MetricSystem, on_delete=models.CASCADE)

	def __str__(self):
		return f"{self.unit} {self.symbol}"


class Product(TimeStampedModel):
	name = models.CharField(max_length=128)
	brand = models.CharField(max_length=128)
	description = models.CharField(max_length=2048, null=True)
	barcode = models.CharField(max_length=128, null=True, unique=True)
	quantity = models.FloatField(default=0)
	stock_limit = models.FloatField(default=0)
	purchase_price = models.IntegerField(null=True)
	metric_system = models.ForeignKey(MetricSystem, on_delete=models.CASCADE)
	purchase_metric = models.ForeignKey(Metric, null=True, on_delete=models.SET_NULL)
	categories = models.ManyToManyField('Category', through='ProductCategories', through_fields=('product', 'category'))

	def __str__(self):
		return self.name

	def stock_value(self):
		quantity_in_default_sale_guide_metric = 0
		default_sale_guide = self.sale_guides.first()
		if default_sale_guide and self.purchase_metric:
			quantity_in_default_sale_guide_metric = self.metric_system.convert(self.quantity, self.purchase_metric, default_sale_guide.metric)
			return quantity_in_default_sale_guide_metric * default_sale_guide.price

	def update_quantity_by(self, quantity, metric):
		if self.purchase_metric!=metric:
			quantity = self.metric_system.convert(quantity, metric, self.purchase_metric)
		self.quantity += quantity
		self.save()

	def convert_quantities(self, old_purchase_metric, new_purchase_metric):
		quantity = self.metric_system.convert(self.quantity, old_purchase_metric, new_purchase_metric)
		stock_limit = self.metric_system.convert(self.stock_limit, old_purchase_metric, new_purchase_metric)
		self.quantity = quantity
		self.stock_limit = stock_limit
		self.save()

	def default_sale_guide(self):
		return self.sale_guides.first()

	def default_sale_guide_metric(self):
		default_sale_guide = self.default_sale_guide()
		if default_sale_guide:
			return default_sale_guide.metric

	def quantity_in_default_sale_guide_metric(self):
		default_sale_guide_metric = self.default_sale_guide_metric()
		purchase_metric = self.purchase_metric
		if default_sale_guide_metric and purchase_metric:
			return self.metric_system.convert(self.quantity, purchase_metric, default_sale_guide_metric)

	def stock_limit_in_default_sale_guide_metric(self):
		default_sale_guide_metric = self.default_sale_guide_metric()
		purchase_metric = self.purchase_metric
		if default_sale_guide_metric and purchase_metric:
			return self.metric_system.convert(self.stock_limit, purchase_metric, default_sale_guide_metric)


class Category(TimeStampedModel):
	name = models.CharField(max_length=128, unique=True)
	products = models.ManyToManyField(Product, through='ProductCategories', through_fields=('category', 'product'))

	def __str__(self):
		return self.name


class ProductCategories(TimeStampedModel):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Stock(TimeStampedModel):
	quantity = models.IntegerField()
	product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)


class SaleGuide(TimeStampedModel):
	metric = models.ForeignKey(Metric, on_delete=models.CASCADE)
	price = models.IntegerField()
	product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='sale_guides')

	def __str__(self):
		return f"{self.price} @ {self.metric}"


class OrderGroup(TimeStampedModel):
	reference = models.CharField(max_length=128)
	closed = models.BooleanField(default=False)
	customer = models.CharField(max_length=256, null=True)
	waiter = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='waiter')
	cashier = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='cashier')
	status = models.SmallIntegerField(choices=STATUS_CHOICES, default=PENDING)

	def __str__(self):
		return self.reference

	def total(self):
		return sum([(order.quantity*order.sale_price) for order in self.order_set.all()])


class Order(TimeStampedModel):
	reference = models.CharField(max_length=128)
	quantity = models.IntegerField()
	product_name = models.CharField(max_length=128)
	purchase_price = models.IntegerField()
	purchase_metric = models.CharField(max_length=128)
	sale_price = models.IntegerField()
	sale_metric = models.CharField(max_length=128)

	order_group = models.ForeignKey(OrderGroup, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
	sale_guide = models.ForeignKey(SaleGuide, null=True, on_delete=models.SET_NULL)

	class Meta:
		permissions = [
			("can_make_orders", "Can make orders"),
			("can_mark_orders_as_ready", "Can mark orders as ready"),
			("can_mark_orders_as_served", "Can mark orders as served"),
		]

	def __str__(self):
		return self.reference



class Purchase(TimeStampedModel):
	quantity = models.IntegerField()
	product_name = models.CharField(max_length=128)
	purchase_price = models.IntegerField()
	purchase_metric = models.CharField(max_length=128)
	product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
	

class Profile(models.Model):
    name = models.CharField(max_length=256)
    email = models.EmailField()
    telephone = models.CharField(max_length=16, null=True)
    user = models.OneToOneField(User, unique=False, on_delete=models.CASCADE)

    def __str__(self):
    	return self.name

    def roles(self):
        return ', '.join([group.name for group in self.user.groups.all()])


def get_user_profile(self):
	if getattr(self, "profile", None):
		return self.profile.name
	return self.username

User.add_to_class("__str__", get_user_profile)

bar/views.py
from django.shortcuts import render

# Create your views here.

bar/views/category.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import TemplateView, DetailView
from ..models import Category
from ..forms import CreateCategoryForm, DeleteCategoryForm, UpdateCategoryForm


def create_category(request):
	create_category_form = CreateCategoryForm()
	if request.method=="POST":
		create_category_form = CreateCategoryForm(request.POST)
		if create_category_form.is_valid():
			data = create_category_form.cleaned_data
			category = Category.objects.create(**data)
			messages.success(request, "Category created")
			return redirect('bar:get_products')
	context = {
		"create_category_form": create_category_form
	}
	return render(request, 'category/create-category.html', context)


def get_category(request, id):
	category = Category.objects.get(id=id)
	update_category_form = UpdateCategoryForm(data={
		"name": category.name
		}, category=category)
	if request.method=="POST":
		update_category_form = UpdateCategoryForm(data=request.POST, category=category)
		if update_category_form.is_valid():
			data = update_category_form.cleaned_data
			category.name = data["name"]
			category.save()
			messages.success(request, "Category updated")
			return redirect('bar:get_products')
	context = {
		"update_category_form": update_category_form,
		"category": category
	}
	return render(request, 'category/category.html', context)


def delete_category(request, id):
	category = Category.objects.get(id=id)
	category.delete()
	messages.success(request, "Category deleted")
	return redirect('bar:get_products')

bar/views/index.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, get_user, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from ..models import User
from ..forms import LoginForm


@login_required
def index(request):
    return redirect('bar:create_orders')

def login_view(request):
    _next = request.GET.get("next", "bar:create_orders")
    if request.method == "POST":
        form = LoginForm(request.POST)
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(username=email, password=password)

        if user:
            login(request, user)
            return redirect(_next)
        else:
            messages.error(request, f"User not found!", extra_tags="danger")
            return redirect("bar:login")
    else:
        if get_user(request).is_authenticated:
            return redirect('bar:create_orders')

        waiters = User.objects.filter(groups__name='Waiter').all()

        form = LoginForm()
        context = {"form": form, "waiters": waiters}
        return render(request, 'index/login.html', context)


def login_waiter(request, id):
    _next = request.GET.get("next", "bar:create_orders")
    user = User.objects.filter(groups__name='Waiter').filter(id=id).first()
    if user:
        login(request, user)
        return redirect(_next)
    messages.error(request, f"Could not identify user")
    return redirect('bar:login')



def forgot_password(request):
    forgot_password_form = ForgotPasswordForm()
    if request.method == "POST":
        forgot_password_form = ForgotPasswordForm(request.POST)
        if forgot_password_form.is_valid():
            cleaned_data = forgot_password_form.cleaned_data
            user = cleaned_data.get("email")
            # set auth token
            set_user_token(user)
            # send email
            send_auth_mail(user.username)
            # send_auth_mail.delay(user.email)
            messages.info(request, f"An email with password reset instructions has been sent to '{user.username}'. Login to your this email to continue.")
            return redirect("bar:create_orders")

    context = {"forgot_password_form": forgot_password_form}
    return render(request, "auth/forgot-password.html", context) 



def logout_view(request):
    logout(request)
    return redirect('bar:login')

bar/views/metric_system.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, get_user, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView, DetailView
from django.contrib import messages
from ..models import MetricSystem
from ..forms import CreateMetricSystemForm
from ..decorators import *
from django.utils.decorators import method_decorator



class MetricSystemsPageView(TemplateView):
	template_name = "metric-system/metric-systems.html"

	def get_context_data(self, ** kwargs):
		context = super().get_context_data(**kwargs)
		create_metric_system_form = CreateMetricSystemForm()
		context['metric_systems'] = MetricSystem.objects.all()
		context["create_metric_system_form"] = create_metric_system_form
		return context
	
	@method_decorator(groups_required("Admin", "Cashier"))
	def get(self, request, *args, **kwargs):
		metric_systems = MetricSystem.objects.all()
		create_metric_system_form = CreateMetricSystemForm()
		context = {
			'metric_systems': metric_systems,
			'create_metric_system_form': create_metric_system_form,
		}
		return render(request, "metric-system/metric-systems.html", context)


@groups_required("Admin", "Cashier")
@login_required
def create_metric_system(request):
	create_metric_system_form = CreateMetricSystemForm(request.POST)
	if create_metric_system_form.is_valid():
		data = create_metric_system_form.cleaned_data
		metric_system = MetricSystem(name=data["name"])
		metric_system.save()
		messages.success(request, "Metric system created.")
		return redirect("bar:get_metric_systems")



@groups_required("Admin", "Cashier")
@login_required
def delete_metric_system(request, id):
	metric_system = MetricSystem.objects.get(id=id)
	metric_system.delete()
	messages.success(request, "Metric System deleted")
	return redirect('bar:get_metric_systems')

bar/views/purchase.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, get_user, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from ..models import Purchase
from ..forms import FilterPurchasesForm

@login_required
def get_purchases(request):
	query = Purchase.objects
	filter_purchases_form = FilterPurchasesForm(data=request.GET)
	if filter_purchases_form.is_valid():
		data = filter_purchases_form.cleaned_data
		date_lte = data.get("date_lte")
		date_gte = data.get("date_gte")
		product = data.get("product")
		if date_lte:
			query = query.filter(created_at__lte=date_lte)
		if date_gte:
			query = query.filter(created_at__gte=date_gte)
		if product:
			query = query.filter(product_id=product)
	purchases = query.order_by("-created_at").all()
	page = int(request.GET.get("page", 1))
	paginator = Paginator(purchases, 50)
	purchases = paginator.get_page(page)
	context = {
		"purchases": purchases,
        "count":len(purchases),
		"total": sum([purchase.quantity*purchase.purchase_price for purchase in purchases]),
		"filter_purchases_form": filter_purchases_form
	}
	return render(request, 'purchase/purchases.html', context)

bar/templates/profile/create-profile.html
{% extends 'base.html' %}
{% load app_tags %}


{% block body %}
	<div id="app">
        {% include 'index/nav.html' %}
        {% include 'index/alert.html' %}
        <div class="d-flex sticky-top bg-light p-2 justify-content-between  border-bottom mb-2">
            <h3 class="my-auto"><a href="{% url 'bar:get_profiles' %}" class="nav-link px-1 d-inline">Users</a> / Create user</h3>
        </div>

        <div class="container-fluid m-0">
        	<div class="container" align="center">
                <div style="max-width: 400px" align="left">
                    <div class="p-2 border mb-2">
                        <strong>Details</strong>
                    </div>
                    <form class="bg-light border border-left" method="POST">
                        {% csrf_token %}
                        {% render_field create_user_form.name %}
                        {% render_field create_user_form.user_group %}
                        {% render_field create_user_form.telephone tel_code=create_user_form.tel_code %}
                        <div v-if="userGroup!=3">
                            <div class="form-group p-2">
                                <label>Email <span v-show="userGroup!=3" class="text-danger">*</span></label> 
                                <input type="email" name="email" id="id_email" class="form-control" :required="userGroup!=3">
                                <small class="text-danger">
                                    {{create_user_form.email.errors}}
                                </small>
                            </div>
                            {% render_field create_user_form.password  %}
                            {% render_field create_user_form.confirm_password %}
                        </div>
                        <div class="p-2 border-top" align="right">
                            <button class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block vue %}
<script type="text/javascript">
    var vue = new Vue({
        el: '#app',
        data: {
            userGroup: 1,
        },
        created: function() {
            
        },
        computed: {
            
        },
        methods: {
            
        }
    });
</script>
{% endblock %}

bar/templates/profile/profile.html
{% extends 'base.html' %}
{% load app_tags %}


{% block body %}
	<div id="app">
        {% include 'index/nav.html' %}
        {% include 'index/alert.html' %}

        <div class="d-flex sticky-top bg-light p-2 justify-content-between  border-bottom mb-2">
	        <h3 class="my-auto"><a href="{% url 'bar:get_profiles' %}" class="nav-link px-1 d-inline">Users</a> / {{profile}}</h3>
	    </div>
		<div class="container">
	        <div class="row">
	        	<div class="col-md-6">
	        		<div class="d-flex justify-content-between p-2 border mb-2">
		                <h4 class="my-auto">User Profile</h4>
		                {% include 'user/delete-user.html' %}
		            </div>

		        	<form method="POST" class="border" action="{% url 'bar:update_user' id=profile.user_id %}" align="left">
						{% csrf_token %}
						{% render_field update_user_form.name %}
						{% if not profile.user|has_group:"Waiter" %}
							{% render_field update_user_form.email %}
						{% endif %}
						{% render_field update_user_form.telephone tel_code=update_user_form.tel_code %}
						{% render_field update_user_form.is_active %}
						<div class="p-2" align="right">
							<button class="btn btn-primary">Update User Profile</button>
						</div>
					</form>
				</div>

	        	<div class="col-md-6">
	        		{% if group.id != 3 %}
	        		<div class="p-2 border mb-2">
		                <h4 class="my-auto">User Password</h4>
		            </div>
		            <form method="POST" class="border" action="{% url 'bar:update_user_password' id=profile.user_id %}" align="left">
		            	{% csrf_token %}
						{% render_field update_user_password_form.new_password %}
						{% render_field update_user_password_form.confirm_password %}
					
						<div class="p-2" align="right">
							<button class="btn btn-primary">Update User Password</button>
						</div>
					</form>
					{% endif %}
	        	</div>
	        </div>
	    </div>

    </div>

{% endblock %}

bar/templates/profile/profiles.html
{% extends 'base.html' %}
{% load app_tags %}


{% block body %}
	<div id="app">
        {% include 'index/nav.html' %}
        {% include 'index/alert.html' %}
    </div>

    <div class="d-flex bg-light p-2 justify-content-between">
        <h3 class="my-auto">Users</h3>
        <a href="{% url 'bar:create_user' %}" class="btn btn-primary">Create User</a>
    </div>

    <div class="overflow-auto">
        <table class="table table-bordered table-hover">
        	<thead>
        		<th>Name</th>
                <th>Group</th>
                <th>Email</th>
        		<th>Telephone</th>
        		<th></th>
        	</thead>

        	<tbody>
        		{% for profile in profiles %}
        		<tr>
                    <td><a href="{% url 'bar:get_profile' id=profile.id %}" class="nav-link p-0">{{profile.name}}</a></td>
                    <td>{{profile.roles}}</td>
        			<td>
                        {{profile.email}}<br>
                    </td>
                    <td>{{profile.telephone}}</td>
        			<td><a href="{% url 'bar:get_profile' id=profile.id %}" class="btn btn-primary btn-sm">View</a></td>
        		</tr>
        		{% endfor %}
        	</tbody>
        </table>
    </div>


{% endblock %}