bar/urls.py
from django.urls import path
from .api import *
from .views import *
from django.views.generic import TemplateView


app_name = "bar"


router = routers.DefaultRouter()
router.register('metrics', MetricViewSet)
router.register('metric-systems', MetricSystemViewSet)
router.register('orders', OrderViewSet)
router.register('order-groups', OrderGroupViewSet)
router.register('products', ProductViewSet)
router.register('profiles', ProfileViewSet)
router.register('sale-guides', SaleGuideViewSet)
router.register('stock', StockViewSet)
router.register('categories', CategoryViewSet)


urlpatterns = [
	url(r'^api/', include(router.urls)),
	path('', index, name='index'),
	path('home', TemplateView.as_view(template_name='pages/trial.html'), name='index'),
	path('login', login_view, name='login'),
	path('login/waiter/<int:id>', login_waiter, name='login_waiter'),
	path('logout', logout_view, name='logout'),
	
	path('orders', orders, name='orders'),
	path('orders/create', create_orders, name='create_orders'),
	# path('orders/update/<int:order_group_id>', update_orders, name='update_orders'),
	path('orders/update/status', update_order_status, name='update_order_status'),
	path('orders/sales', get_order_sales, name='get_order_sales'),
	
	path('order-groups', get_order_groups, name='get_order_groups'),
	path('order-groups/<int:id>', get_order_group, name='get_order_group'),
	path('order-groups/<int:id>/update', update_order_group, name='update_order_group'),
	path('order-groups/<int:id>/open-or-close', open_or_close_order_group, name='open_or_close_order_group'),
	path('order-groups/<int:id>/delete', delete_order_group, name='delete_order_group'),
	
	path('purchases', get_purchases, name='get_purchases'),

	path('profile', get_current_user_profile, name='get_current_user_profile'),
	path('profile/update', update_current_user_profile, name='update_current_user_profile'),
	path('profile/password/update', update_current_user_password, name='update_current_user_password'),

	path('profiles', get_profiles, name='get_profiles'),
	path('profiles/<int:id>', get_profile, name='get_profile'),
	path('users/create', create_user, name='create_user'),
	path('users/<int:id>', update_user, name='update_user'),
	path('users/<int:id>/delete', delete_user, name='delete_user'),
	path('users/<int:id>/password/update', update_user_password, name='update_user_password'),
	path('users/<int:id>/permissions/update', update_user_permissions, name='update_user_permissions'),


	path('metric-systems', MetricSystemsPageView.as_view(), name='get_metric_systems'),
	path('metric-systems/create', create_metric_system, name='create_metric_system'),
	path('metric-systems/<int:id>/delete', delete_metric_system, name='delete_metric_system'),

	path('products', get_products, name='get_products'),
	path('products/create', create_product, name='create_product'),
	path('products/<int:id>/', get_product, name='get_product'),
	path('products/<int:id>/purchasing/update', update_product_purchasing, name='update_product_purchasing'),
	path('products/<int:id>/delete', delete_product, name='delete_product'),
	path('products/<int:id>/categories/update', update_product_categories, name='update_product_categories'),
	path('products/<int:id>/stock/add', add_product_stock, name='add_product_stock'),

	path('categories/create', create_category, name='create_category'),
	path('categories/<int:id>/', get_category, name='get_category'),
	path('categories/<int:id>/delete', delete_category, name='delete_category'),

	path('notifications', get_notifications, name='get_notifications'),
	path('notifications/count', get_notification_count, name='get_notification_count'),

]

bar_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('bar.urls', namespace='bar')),
]

bar/forms/metric_system.py
from django import forms
from ..models import User
from django.contrib.auth import authenticate


class CreateMetricSystemForm(forms.Form):
	name = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))

bar/views.py
from django.shortcuts import render

# Create your views here.

bar/views/category.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import TemplateView, DetailView
from ..models import Category
from ..forms import CreateCategoryForm, DeleteCategoryForm, UpdateCategoryForm


def create_category(request):
	create_category_form = CreateCategoryForm()
	if request.method=="POST":
		create_category_form = CreateCategoryForm(request.POST)
		if create_category_form.is_valid():
			data = create_category_form.cleaned_data
			category = Category.objects.create(**data)
			messages.success(request, "Category created")
			return redirect('bar:get_products')
	context = {
		"create_category_form": create_category_form
	}
	return render(request, 'category/create-category.html', context)


def get_category(request, id):
	category = Category.objects.get(id=id)
	update_category_form = UpdateCategoryForm(data={
		"name": category.name
		}, category=category)
	if request.method=="POST":
		update_category_form = UpdateCategoryForm(data=request.POST, category=category)
		if update_category_form.is_valid():
			data = update_category_form.cleaned_data
			category.name = data["name"]
			category.save()
			messages.success(request, "Category updated")
			return redirect('bar:get_products')
	context = {
		"update_category_form": update_category_form,
		"category": category
	}
	return render(request, 'category/category.html', context)


def delete_category(request, id):
	category = Category.objects.get(id=id)
	category.delete()
	messages.success(request, "Category deleted")
	return redirect('bar:get_products')

bar/views/index.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, get_user, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from ..models import User
from ..forms import LoginForm


@login_required
def index(request):
    return redirect('bar:create_orders')

def login_view(request):
    _next = request.GET.get("next", "bar:create_orders")
    if request.method == "POST":
        form = LoginForm(request.POST)
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(username=email, password=password)

        if user:
            login(request, user)
            return redirect(_next)
        else:
            messages.error(request, f"User not found!", extra_tags="danger")
            return redirect("bar:login")
    else:
        if get_user(request).is_authenticated:
            return redirect('bar:create_orders')

        waiters = User.objects.filter(groups__name='Waiter').all()

        form = LoginForm()
        context = {"form": form, "waiters": waiters}
        return render(request, 'index/login.html', context)


def login_waiter(request, id):
    _next = request.GET.get("next", "bar:create_orders")
    user = User.objects.filter(groups__name='Waiter').filter(id=id).first()
    if user:
        login(request, user)
        return redirect(_next)
    messages.error(request, f"Could not identify user")
    return redirect('bar:login')



def forgot_password(request):
    forgot_password_form = ForgotPasswordForm()
    if request.method == "POST":
        forgot_password_form = ForgotPasswordForm(request.POST)
        if forgot_password_form.is_valid():
            cleaned_data = forgot_password_form.cleaned_data
            user = cleaned_data.get("email")
            # set auth token
            set_user_token(user)
            # send email
            send_auth_mail(user.username)
            # send_auth_mail.delay(user.email)
            messages.info(request, f"An email with password reset instructions has been sent to '{user.username}'. Login to your this email to continue.")
            return redirect("bar:create_orders")

    context = {"forgot_password_form": forgot_password_form}
    return render(request, "auth/forgot-password.html", context) 



def logout_view(request):
    logout(request)
    return redirect('bar:login')

bar/views/metric_system.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, get_user, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView, DetailView
from django.contrib import messages
from ..models import MetricSystem
from ..forms import CreateMetricSystemForm
from ..decorators import *
from django.utils.decorators import method_decorator



class MetricSystemsPageView(TemplateView):
	template_name = "metric-system/metric-systems.html"

	def get_context_data(self, ** kwargs):
		context = super().get_context_data(**kwargs)
		create_metric_system_form = CreateMetricSystemForm()
		context['metric_systems'] = MetricSystem.objects.all()
		context["create_metric_system_form"] = create_metric_system_form
		return context
	
	@method_decorator(groups_required("Admin", "Cashier"))
	def get(self, request, *args, **kwargs):
		metric_systems = MetricSystem.objects.all()
		create_metric_system_form = CreateMetricSystemForm()
		context = {
			'metric_systems': metric_systems,
			'create_metric_system_form': create_metric_system_form,
		}
		return render(request, "metric-system/metric-systems.html", context)


@groups_required("Admin", "Cashier")
@login_required
def create_metric_system(request):
	create_metric_system_form = CreateMetricSystemForm(request.POST)
	if create_metric_system_form.is_valid():
		data = create_metric_system_form.cleaned_data
		metric_system = MetricSystem(name=data["name"])
		metric_system.save()
		messages.success(request, "Metric system created.")
		return redirect("bar:get_metric_systems")



@groups_required("Admin", "Cashier")
@login_required
def delete_metric_system(request, id):
	metric_system = MetricSystem.objects.get(id=id)
	metric_system.delete()
	messages.success(request, "Metric System deleted")
	return redirect('bar:get_metric_systems')

bar/views/notification.py
from datetime import datetime
from django.db.models import F
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, get_user, logout
from django.contrib.auth.decorators import login_required
from rest_framework.response import Response
from django.http import JsonResponse
from ..models import Product, Order, OrderGroup
from bar.api import ProductSerializer, OrderGroupSerializer


class Notification:

	def __init__(self, title, description, url, tag=""):
		self.title = title
		self.description = description
		self.url = url
		self.tag = tag


@login_required
def get_notifications(request):
	# low stock products
	low_stock_products = Product.objects.filter(quantity__lte=F("stock_limit")).all()
	# pending orders
	pending_orders = OrderGroup.objects.filter(status=0).all()
	# ready orders
	ready_orders = OrderGroup.objects.filter(status=1).all()
	notifications = []
	for order_group in pending_orders:
		notification = Notification("Pending Order", f"The order '{order_group}' is pending", reverse("bar:orders"))
		notifications.append(notification)

	for order_group in ready_orders:
		notification = Notification("Ready Order", f"The order '{order_group}' is ready", reverse("bar:orders")+"?status=1")
		notifications.append(notification)
	for product in low_stock_products:
		notification = Notification("Low Stock", f"The product '{product}' has low stock", f"/products/{product.id}", tag="danger")
		notifications.append(notification)

	context = {
		"notifications": notifications,
	}
	return render(request, 'notification/notifications.html', context)


	# res = [
	# 	{
	# 		"message": f"{len(low_stock_products)} Product(s) with low stock!",
	# 		"items": low_stock_products,
	# 		"url": reverse("bar:get_products")
	# 	}, 
	# 	{
	# 		"message": f"{len(pending_orders)} Pending Orders",
	# 		"items":pending_orders,
	# 		"url": reverse("bar:orders")
	# 	}, 
	# 	{
	# 		"message": f"{len(ready_orders)} Ready Orders",
	# 		"items":ready_orders,
	# 		"url": reverse("bar:orders")+"?status=1"
	# 	}, 
	# ]
	# return JsonResponse(res, safe=False)


@login_required
def get_notification_count(request):
	# low stock products
	low_stock_products = Product.objects.filter(quantity__lte=F("stock_limit")).count()
	# pending orders
	pending_orders = OrderGroup.objects.filter(status=0).count()
	# ready orders
	ready_orders = OrderGroup.objects.filter(status=1).count()
	return JsonResponse({"count":low_stock_products+pending_orders+ready_orders})

bar/views/order.py
from datetime import datetime
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, get_user, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages
from ..models import Order, OrderGroup
from ..forms import FilterOrderGroupsForm, FilterOrdersForm
from ..utils import STATUS_CHOICES



@login_required
def create_orders(request):
    return render(request, 'pages/create-orders.html')


@login_required
def orders(request):
    status = request.GET.get("status", 0)
    filter_orders_form = FilterOrderGroupsForm(v_model=True)
    context = {
        "status": int(status),
        "filter_orders_form": filter_orders_form
    }
    return render(request, 'pages/orders.html', context)


@login_required
def update_order_status(request):
    if request.method == "POST":
        check = request.POST.get("check")
        ref = request.POST.get("ref")
        status = int(request.POST.get("status", 0))
        
        order = OrderGroup.objects.get(reference=ref)
        if order and status:
            order.status = status
            order.save()
        
            status_value = dict(STATUS_CHOICES)[status]
            messages.success(request, f"Order {ref} has been marked as {status_value}")
            return redirect(reverse('bar:orders') + f'?status={int(status)-1}')



@login_required
def get_order_sales(request):
    query = Order.objects
    filter_orders_form = FilterOrdersForm(data=request.GET)
    if filter_orders_form.is_valid():
        data = filter_orders_form.cleaned_data
        date_lte = data.get("date_lte")
        date_gte = data.get("date_gte")
        product = data.get("product")
        if date_lte:
            query = query.filter(created_at__lte=date_lte)
        if date_gte:
            query = query.filter(created_at__gte=date_gte)
        if product:
            query = query.filter(product_id=product)
    orders = query.order_by("-created_at").all()
    page = int(request.GET.get("page", 1))
    paginator = Paginator(orders, 50)
    orders = paginator.get_page(page)
    context = {
        "orders":orders,
        "count":len(orders),
        "total": sum([order.quantity*order.sale_price for order in orders]),
        "filter_orders_form": filter_orders_form
    }
    return render(request,'order/order-sales.html', context)

bar/views/order_group.py
from datetime import datetime
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, get_user, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect 
from django.contrib import messages
from django.core.paginator import Paginator
from ..models import OrderGroup
from ..forms import FilterOrderGroupsForm
from ..utils import STATUS_CHOICES



@login_required
def get_order_groups(request):
    query = OrderGroup.objects
    filter_order_groups_form = FilterOrderGroupsForm(data=request.GET)
    if filter_order_groups_form.is_valid():
        data = filter_order_groups_form.cleaned_data
        date_lte = data.get("date_lte")
        date_gte = data.get("date_gte")
        status = data.get("status")
        if date_lte:
            query = query.filter(created_at__lte=date_lte)
        if date_gte:
            query = query.filter(created_at__gte=date_gte)
        if isinstance(status, bool):
            query = query.filter(closed=status)


    order_groups = query.order_by("-created_at").all()
    page = int(request.GET.get("page", 1))
    paginator = Paginator(order_groups, 50)
    order_groups = paginator.get_page(page)
    context = {
        "order_groups": order_groups,
        "total": sum([order_group.total() for order_group in order_groups]),
        "filter_order_groups_form": filter_order_groups_form,
    }
    return render(request, 'order_group/order-groups.html', context)
    

@login_required
def get_order_group(request, id):
    order_group = OrderGroup.objects.get(id=id)
    context = {
        "order_group": order_group,
        "orders": order_group.order_set.all()
    }
    return render(request, "order_group/order-group.html", context)



@login_required
def update_order_group(request, id):
    order_group = OrderGroup.objects.get(id=id)
    context = {
        "order_group": order_group
    }
    return render(request, 'pages/update-orders.html', context)


@login_required
def open_or_close_order_group(request, id):
    order_group = OrderGroup.objects.get(id=id)
    order_group.closed = not order_group.closed
    status = "OPENED"
    if order_group.closed: status = "CLOSED"
    messages.success(request, f"Order {status}")
    order_group.save()
    next = request.META.get('HTTP_REFERER', None) or '/'
    return HttpResponseRedirect(next)


@login_required
def delete_order_group(request, id):
    order_group = OrderGroup.objects.get(id=id)
    ref = order_group.reference
    order_group.delete()
    messages.success(request, f"Deleted order {ref}")
    return redirect('bar:orders')

bar/templates/index/alert.html
{% if messages %}
	{% for message in messages %}
		<div class="alert m-0 alert-{{ message.tags }} alert-dismissible fade show rounded-0 border-left-0 border-right-0" role="alert">
		  {{message}}
		  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	{% endfor %}
{% endif %}

bar/templates/index/index.html
{% extends 'base.html' %}


{% block body %}

	{% include 'index/nav.html' %}

	{% include 'order/orders.html' %}

{% endblock %}

bar/templates/index/loading.html
<div class="modal-backdrop show" style="opacity: 0.3"></div>
<div class="modal show p-0" id="loadModal" tabindex="-1" data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-modal="true" role="dialog" style="padding-right: 14px; display: block;">
    <div class="modal-dialog modal-dialog-centered" align="center">
        <div class="modal-body text-center">
            <div class="spinner-border text-primary" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </div>
</div>

bar/templates/index/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load app_tags %}

{% block body %}
	<div class="container" align="center">
		<div align="center">
			<img style="height: 150; width: 150" src="{% static 'img/logo.png' %}" />
		</div>

		<div>
			<h1 class="text-dark text-center">Welcome to {% settings_value "APP_NAME" %}</h1>	
		</div>

		<div class="border bg-light rounded-top" style="max-width:400; min-height: 300">
			
			<ul class="d-flex nav nav-pills p-2 justify-content-center" id="pills-tab" role="tablist">
				<!-- <li class="nav-item" role="presentation">
					<button class="nav-link active" id="pills-waiter-tab" data-bs-toggle="pill" data-bs-target="#pills-waiter" type="button" role="tab" aria-controls="pills-waiter" aria-selected="false">Waiter</button>
				</li> -->
				<li class="nav-item" role="presentation">
					<button class="nav-link active" id="pills-login-tab" data-bs-toggle="pill" data-bs-target="#pills-login" type="button" role="tab" aria-controls="pills-login" aria-selected="true">Login</button>
				</li>
			</ul>
			{% include 'index/alert.html' %}
			<div class="tab-content" id="pills-tabContent">
				<!-- <div class="tab-pane fade show active p-2" id="pills-waiter" role="tabpanel" aria-labelledby="pills-waiter-tab"  align="left">
					<ul class="list-group">
						{% for waiter in waiters %}
							<a class="nav-link" href="{% url 'bar:login_waiter' id=waiter.id %}">
								<li class="d-flex justify-content-between list-group-item list-group-item-action my-1 border rounded hover-scale">
									{{waiter.profile}}
									<span class="fa fa-arrow-right my-auto"></span>
								</li>
							</a>
						{% empty %}
							<p class="text-center text-muted">There are no registered waiters</p>
						{% endfor %}
					</ul>
				</div> -->
				<div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="pills-login-tab">
					<form class="m-0" method="POST" action="" align="left">
						{% csrf_token %}
						
						{% render_field form.email class='form-control' %}
						{% render_field form.password class='form-control' %}
						
						<div align="center" class="bg-white border-top p-3 mt-3 mb-0">
							<button class="btn btn-primary">Login <span class="fa fa-sign-in"></span></button>
							<!-- <a href="" class="nav-link">Forgot Password</a> -->
						</div>
					</form>
				</div>
			</div>

			
		</div>
	</div>
{% endblock %}

bar/templates/index/nav.html
{% load static %}
{% load app_tags %}
<nav class="navbar navbar-expand-lg navbar-light bg-primary text-light px-0">
    <div class="container-fluid px-1">
        <div class="my-auto">
            <h3 class="d-inline m-0" href="">{% settings_value "APP_NAME" %}</h3>
        </div>
    
        <div>

            <a href="{% url 'bar:create_orders' %}" class="btn btn-primary f-10"><strong>+</strong></span></a>
            <a href="{% url 'bar:orders' %}" class="btn btn-primary"><span class="fa fa-bell-o fa-2x"></span></a>
            <button id="navButton" class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="notifications" class="dropdown d-inline">
                
            </div>
        </div>
    </div>
</nav>

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header bg-primary">
        <h4 id="offcanvasRightLabel" class="text-white text-center flex-fill my-auto">{{user}} <small>({{user.profile.roles}})</small></h4>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <div class="d-flex flex-wrap justify-content-around">
            <a href="{% url 'bar:create_orders' %}" class="m-2 nav-link border border-primary border-2 p-3 rounded hover-scale">
                <div align="center" class="text-center" style="height: 5.5rem; width: 5.5rem" class="card">
                    <img class="img-thumbnail" src="{% static 'img/new-order.png' %}" style="height: 5rem; width: 5rem"/>
                    New Order
                </div>
            </a>
            
            <a href="{% url 'bar:orders' %}" class="m-2 nav-link border border-primary border-2 p-3 rounded hover-scale">
                <div align="center" class="text-center" style="height: 5.5rem; width: 5.5rem" class="card">
                    <img class="img-thumbnail" src="{% static 'img/orders.jpg' %}" style="height: 5rem; width: 5rem"/>
                    Orders
                </div>
            </a>
            
            {% if not user|has_group:"Waiter" %}
            <a href="{% url 'bar:get_current_user_profile' %}" class="m-2 nav-link border border-primary border-2 p-3 rounded hover-scale">
                <div align="center" class="text-center" style="height: 5.5rem; width: 5.5rem" class="card">
                    <img src="{% static 'img/user.png' %}" style="height: 5rem; width: 5rem"/>
                    Your Account
                </div>
            </a>
            {% endif %}

            <a href="{% url 'bar:logout' %}" class="m-2 nav-link border border-primary border-2 p-3 rounded hover-scale">
                <div align="center" class="text-center" style="height: 5.5rem; width: 5.5rem" class="card">
                    <img src="{% static 'img/logout.jpg' %}" style="height: 5rem; width: 5rem"/>
                    Logout
                </div>
            </a>
        </div>


        {% if not user|has_group:"Waiter" %}
        <hr>
        <div class="d-flex flex-wrap justify-content-around">


            <a href="{% url 'bar:get_order_sales' %}" class="m-2 nav-link border border-primary border-2 p-3 rounded hover-scale">
                <div align="center" class="text-center" style="height: 5.5rem; width: 5.5rem" class="card">
                    <img src="{% static 'img/all-orders.jpeg' %}" style="height: 5rem; width: 5rem"/>
                    Sales
                </div>
            </a>

            <a href="{% url 'bar:get_purchases' %}" class="m-2 nav-link border border-primary border-2 p-3 rounded hover-scale">
                <div align="center" class="text-center" style="height: 5.5rem; width: 5.5rem" class="card">
                    <img src="{% static 'img/purchases.png' %}" style="height: 5rem; width: 5rem"/>
                    Purchases
                </div>
            </a>

            <a href="{% url 'bar:get_products' %}" class="m-2 nav-link border border-primary border-2 p-3 rounded hover-scale">
                <div align="center" class="text-center" style="height: 5.5rem; width: 5.5rem" class="card">
                    <img src="{% static 'img/products.png' %}" style="height: 5rem; width: 5rem"/>
                    Inventory
                </div>
            </a>

            <a href="{% url 'bar:get_metric_systems' %}" class="m-2 nav-link border border-primary border-2 p-3 rounded hover-scale">
                <div align="center" class="text-center" style="height: 5.5rem; width: 5.5rem" class="card">
                    <img src="{% static 'img/metrics.png' %}" style="height: 5rem; width: 5rem"/>
                    Metrics
                </div>
            </a>


            {% if not user|has_group:"Cashier" %}
            <a href="{% url 'bar:get_profiles' %}" class="m-2 nav-link border border-primary border-2 p-3 rounded hover-scale">
                <div align="center" class="text-center" style="height: 5.5rem; width: 5.5rem" class="card">
                    <img src="{% static 'img/users.png' %}" style="height: 5rem; width: 5rem"/>
                    Users
                </div>
            </a>
            {% endif %}
        </div>
        {% endif %}
    </div>
</div>

bar/templates/index/notification-bar.html
<div id="notification" v-if="alertCount">
	<template>
			<span id="alertCount" class="badge rounded-pill bg-danger">
			     {%verbatim%}{{alertCount}}{%endverbatim%}
			</span>
	</template>
</div>

bar/templates/index/paginator.html
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if objects.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ objects.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
        {% endif %}
        {% for i in objects.paginator.page_range %}
            {% if objects.number == i %}
            <li class="page-item active">
                <a class="page-link" href="#">{{i}}</a>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if objects.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ objects.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
        {% endif %}
    </ul>
</div>

bar/templates/index/warning.html
<div class="modal-backdrop show" style="opacity: 0.3"></div>
<div class="modal show p-0" id="loadModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-modal="true" role="dialog" style="padding-right: 14px; display: block;">
    <!-- <div class="modal-dialog modal-dialog-centered" align="center">
        <div class="modal-body text-center">
            <div class="spinner-border text-primary" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </div> -->
    <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Warning</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Hello, this is the message.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Understood</button>
      </div>
    </div>
  </div>
</div>